name: munafa_khor
description: A Flutter project for Munafa Khor
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'  # Updated to support Flutter 3.29.0+

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8  # Updated to latest version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  # Added for better code quality

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png